name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Build Project
      run: |
        npm install
        npm run build
        npm prune --production

    - name: Create Vercel Project
      run: |
        cd .
        PROJECT_ID=$(vercel projects add ${{ github.event.repository.name }} --project-settings="{ 'framework': 'nextjs' }" --token=${{ secrets.VERCEL_TOKEN }} --confirm | sed -n 's/.*\\(https:\\/\\/vercel.com\\/[^/]*\\/[^/]*\\).*/\\1/p')
        echo "VERCEL_PROJECT_URL=$PROJECT_ID" >> $GITHUB_ENV

    - name: Deploy Project to Vercel
      run: |
        cd .
        vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm