name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: |
        npm uninstall -g vercel
        npm install -g vercel@latest

    - name: Build Project
      run: |
        npm install
        npm run build
        npm prune --production

    - name: Create Vercel Project
      run: |
        cd .
        PROJECT_ID=$(vercel projects add ${{ github.event.repository.name }} --token=${{ secrets.VERCEL_TOKEN }} --confirm | sed -n 's/.*\\(https:\\/\\/vercel.com\\/[^/]*\\/[^/]*\\).*/\\1/p')
        echo "VERCEL_PROJECT_URL=$PROJECT_ID" >> $GITHUB_ENV

    - name: Set Vercel Project Settings
      run: |
        vercel env pull --yes ${{ secrets.VERCEL_TOKEN }}
        vercel env set NEXT_PUBLIC_FRAMEWORK=nextjs --yes ${{ secrets.VERCEL_TOKEN }}
        vercel env push ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project to Vercel
      run: |
        cd .
        vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm